- hosts: wp_servers 
  tasks:
    - name: install server dep
      become: yes
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd24
        - mysql57-server
        - php71
    - name: "retrieve wp archive"
      unarchive:
        src: https://pl.wordpress.org/wordpress-4.9.4-pl_PL.tar.gz
        dest: /tmp
        remote_src: true
